# Generated by Django 4.1.7 on 2023-03-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('pno', models.CharField(max_length=50, verbose_name='')),
                ('email', models.CharField(max_length=50, verbose_name='')),
                ('feedback', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
    ]
